seed: 420

experiment_name: "finetune_car"
experiment_class: FinetuneResnet
dataset: car
resize: 224

n_epochs: 1
batch_size: 128

optim_name: sgd
learning_rate: 0.05
weight_decay: 0
momentum: 0

model_name: resnet
model_size: 50
